### ISSUE TITLE
ERROR after answering ?!!

### ISSUE THREAD

**Issue by Amrlol** [kalliope-project/kalliope_neuron_answer_of_everything#3]
When i ask kalliope a quesion it answers me and  then this error appears !!!

Google Speech Recognition thinks you said I have a question what time is it in Tokyo
Order matched in the brain. Running synapse "say-local-date" 

Order matched in the brain. Running synapse "answer-of-everything-short"
it's 21 and 45 minute
Short answer found: 3:45:33 A.M. JST, Sunday, September 30, 2018

ERROR STARTS HERE :-

Exception in thread <class 'kalliope.signals.order.order.Order'>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/signals/order/order.py", line 87, in run
    self.start_trigger()
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 1059, in _process
    self._transition_queue[0]()
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 399, in _trigger
    return self._process(event_data)
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 409, in _process
    if trans.execute(event_data):
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 263, in execute
    self._change_state(event_data)
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 274, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 120, in enter
    event_data.machine.callback(handle, event_data)
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 1005, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/signals/order/order.py", line 185, in analysing_order_thread
    is_api_call=False)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/SynapseLauncher.py", line 104, in run_matching_synapse_from_order
    execdata = lifo_buffer.execute(is_api_call=is_api_call)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 109, in execute
    self._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 139, in _process_synapse_list
    self._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 173, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/NeuronLauncher.py", line 62, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/NeuronLauncher.py", line 44, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "resources/neurons/answer_of_everything/answer_of_everything.py", line 43, in __init__
    self.say(answer)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/NeuronModule.py", line 149, in say
    tts_message = self._get_message_from_dict(message)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/NeuronModule.py", line 197, in _get_message_from_dict
    returned_message = self._get_file_template(self.file_template, message_dict)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/NeuronModule.py", line 217, in _get_file_template
    t = Template(cls._get_content_of_file(real_file_template_path))
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 945, in __new__
    return env.from_string(source, template_class=cls)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 1, in template
TemplateSyntaxError: tag name expected

 @Sispheor

**Comment by Amrlol** [comment]
@corus87  ???

**Comment by corus87** [comment]
It looks like there is a syntax error in your file template on line 1.
Show us the content of your file template and we can have a look whats wrong.

**Comment by Amrlol** [comment]
the attached tmplate code has a missing end if in the end . 
and that seemed to solve the problem ~

**Comment by corus87** [comment]
Ohh yes my bad, thanks for info!
