### ISSUE TITLE
Error with translate

### ISSUE THREAD

**Issue by omoioli** [kalliope-project/kalliope_neuron_answer_of_everything#4]
Hi,
I installed this neurons, and it's look very impressive. but it make me an error with the googletranslate's API.
Without the option translate: "fr", the responses are ok, but in english, and my english is so poor ...
With the option to translate, Kalliope fix, and the debug mode show me an error with the googletranslate code, line 53, empty argument ...
I use Python 2.7 and the last version of kalliope on Rpi.
I hav'nt my pi here, but if you want, i'll past the kalliope's debug tomorow.

And sorry for my little level in english ...

**Comment by omoioli** [comment]
This is my kalliope's debug : 
Order matched in the brain. Running synapse "answer-of-everything-spoken"
2019-03-13 08:21:35 :: kalliope-0.5.3 :: Order matched in the brain. Running synapse "answer-of-everything-spoken"
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [NeuronParameterLoader._associate_order_params_to_values] user order: j'ai une question à la hauteur de la tour eiffel, order from synapse: j'ai une question {{ query }}
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [NeuronParameterLoader.get_parameters]Parameters for order: {'query': u'\xe0 la hauteur de la tour eiffel'}
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [Cortex] place parameters in temp list: {'query': u'\xe0 la hauteur de la tour eiffel'}
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [HookManager] calling synapses in hook name: on_order_found
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [HookManager] hook: on_order_found , type: <type 'NoneType'>
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [SynapseLauncher] start_synapse_by_list_name called with synapse list: None 
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [LIFOBuffer] Add a new synapse list to process to the LIFO
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [LIFOBuffer] number of synapse list to process: 1
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [LIFOBuffer] number of neuron to process: 1
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [LIFOBuffer] process_neuron_list: is_api_call: False
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [NeuronLauncher] replacing brackets from {'is_api_call': False, 'option': 'ShortAnswer', 'question': '{{ query }}', 'key': 'TKLLY8-XH8PT62HG5', 'translate': 'fr', 'file_template': 'templates/answers.j2'}, using {'query': u'\xe0 la hauteur de la tour eiffel'}
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [NeuronLauncher] replacing brackets from False, using {'query': u'\xe0 la hauteur de la tour eiffel'}
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [NeuronLauncher] replacing brackets from ShortAnswer, using {'query': u'\xe0 la hauteur de la tour eiffel'}
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [NeuronLauncher] replacing brackets from {{ query }}, using {'query': u'\xe0 la hauteur de la tour eiffel'}
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [NeuronLauncher] replacing brackets from TKLLY8-XH8PT62HG5, using {'query': u'\xe0 la hauteur de la tour eiffel', 'kalliope_memory': {'kalliope_last_order': u"j'ai une question \xe0 la hauteur de la tour Eiffel", 'kalliope_last_tts_message': 'Oui?'}, 'raspivid': 'sudo python /home/pi/kalliope_starter_fr/resources/signal/pirOn.py', 'name': 'monsieur'}
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [NeuronLauncher] replacing brackets from fr, using {'query': u'\xe0 la hauteur de la tour eiffel', 'kalliope_memory': {'kalliope_last_order': u"j'ai une question \xe0 la hauteur de la tour Eiffel", 'kalliope_last_tts_message': 'Oui?'}, 'raspivid': 'sudo python /home/pi/kalliope_starter_fr/resources/signal/pirOn.py', 'name': 'monsieur'}
2019-03-13 08:21:35 :: kalliope-0.5.3 :: Run neuron: "{'name': 'answer_of_everything', 'parameters': {'is_api_call': False, 'option': 'ShortAnswer', 'question': '\xc3\xa0 la hauteur de la tour eiffel', 'key': 'TKLLY8-XH8PT62HG5', 'translate': 'fr', 'file_template': 'templates/answers.j2'}}"
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [Utils]-> get_dynamic_class_instantiation : package path : kalliope.neurons.answer_of_everything.answer_of_everything
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [Utils]-> get_dynamic_class_instantiation : loading path : resources/neurons/answer_of_everything/answer_of_everything.py, as package Answer_of_everything
2019-03-13 08:21:35 :: kalliope-0.5.3 :: [NeuronModule] TTS args: {'name': 'pico2wave', 'parameters': {'cache': True, 'language': 'fr-FR'}}
Exception in thread <class 'kalliope.signals.order.order.Order'>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/kalliope/signals/order/order.py", line 87, in run
    self.start_trigger()
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 1060, in _process
    self._transition_queue[0]()
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 399, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 409, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 263, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 274, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 120, in enter
    event_data.machine.callback(handle, event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 1005, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/signals/order/order.py", line 185, in analysing_order_thread
    is_api_call=False)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/SynapseLauncher.py", line 104, in run_matching_synapse_from_order
    execdata = lifo_buffer.execute(is_api_call=is_api_call)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 109, in execute
    self._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 139, in _process_synapse_list
    self._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 173, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 62, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 44, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "resources/neurons/answer_of_everything/answer_of_everything.py", line 24, in __init__
    question = self.translate_question(question)
  File "resources/neurons/answer_of_everything/answer_of_everything.py", line 47, in translate_question
    text = translator.translate(text, dest='en', src=self.translate).text
  File "/usr/local/lib/python2.7/dist-packages/googletranslate/client.py", line 123, in translate
    data = self._translate(text, dest, src)
  File "/usr/local/lib/python2.7/dist-packages/googletranslate/client.py", line 69, in _translate
    token = self.token_acquirer.do(text)
  File "/usr/local/lib/python2.7/dist-packages/googletranslate/gtoken.py", line 180, in do
    self._update()
  **File "/usr/local/lib/python2.7/dist-packages/googletranslate/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'**

I think this is an issue with the googletranslate's API. Anyway to solve it ?

**Comment by corus87** [comment]
Hi, some month ago google changed there API and we used this neuron with an now outdated python package.
I have changed the python package to googletrans, it should be working now again.

**Comment by omoioli** [comment]
Ok, thx, i try it to change the package so. I think i can close this issue ...

**Comment by omoioli** [comment]
Before, close this issue, i would like to explain the solution that work for me :
uninstall googletranslate API :
```
sudo pip uninstall googletranslate
```
install googletrans
```
sudo pip install googletrans
```
and edit answer_of_everything.py :
```
delete : from googletranslate import translator 
edit : from googletrans import Translator
modify :
    def translate_question(self, text):
        translator=Translator()
        text = translator.translate(text, dest='en', src=self.translate).text
        Utils.print_info('Translated question to: %s' % text)
        return text
    
    def translate_answer(self, text):
        translator=Translator()
        text = translator.translate(text, dest=self.translate, src='en').text
        Utils.print_info('Translated answer to: %s' % text)
        return text 
```
And it's done for me, works great

**Comment by corus87** [comment]
The other possible solution would be, remove the old neuron and reinstall the new one :)

**Comment by omoioli** [comment]
sorry, yes i don't understood you've updated the code... I'm so bad ...
